### PR TITLE
Update for Rails 4

### PR DESCRIPTION
**Pull request by texasjusticar**
https://bostonlogic.atlassian.net/browse/BDT-2464

2 things needed to be updated to get this to Rails 4 compatibility.  I admit I haven't run valid specs yet for this, but it blocks other people from being able to run Rails4 locally for their stories so I'm pushing up what I have and we can fix it later if it ends up not being 100%

1. Update scopes/relationships to match Rails4 syntax
1. `register_javascript_expansion` is gone so put the asset in a conventional spot and expose it for the parent app to include.
1. version bump to 0.1.0, which once this is merged I"ll tag that commit as 0.1.0 so we can bundle to it.

### CODE REVIEW

**Comment by joeheald85** [comment]
@texasjusticar Updates look good to me

**Comment by omundu** [comment]
@texasjusticar are we not using `dynamic_forms_prototype.js` anywhere? or is that being handled elsewhere?

**Comment by texasjusticar** [comment]
@joeheald85  and I discussed offline and it looks like we're now using dynamic_forms_jquery.js instead which is in one_system already.

**Comment by omundu** [comment]
@texasjusticar neat!

**Review by omundu — APPROVED** [review]
🐑

**Pull request merged**
